version: "3.8"

services: 
    traefik:
        image: traefik:v2.2
        command: 
            - --providers.docker
            #- --api.insecure=true
            #- --api.dashboard=true # <== Enabling the dashboard to view services, middlewares, routers, etc...
            - --providers.docker.network=web
            ## Entrypoints Settings - https://docs.traefik.io/routing/entrypoints/#configuration ##
            - --entrypoints.web.address=:80 # <== Defining an entrypoint for port :80 named web
            - --entrypoints.web-secured.address=:443 # <== Defining an entrypoint for https on port :443 named web-secured
             ## Certificate Settings (Let's Encrypt) -  https://docs.traefik.io/https/acme/#configuration-examples ##
            - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true # <== Enable TLS-ALPN-01 to generate and renew ACME certs
            - --certificatesresolvers.mytlschallenge.acme.email=regemdeu@gmail.com # <== Setting email for certs
            - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json # <== Defining acme file to store cert information
        
        ports:
            # The HTTP port
            - "80:80"
            # - "8070:8080" # <== :8080 is where the dashboard runs on
            - "443:443"
        volumes:
            - ./letsencrypt:/letsencrypt # <== Volume for certs (TLS)
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock
        networks: 
            - web
        # labels:
        #     #### Labels define the behavior and rules of the traefik proxy for this container ####
        #     - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
        #     - "traefik.http.routers.api.rule=Host(`dashboard.iopk.in`)" # <== Setting the domain for the dashboard
        #     - "traefik.http.routers.api.service=api@internal" # <== Enabling the api to be a service to access
        
networks: 
    web:
        external: true
